# Generated by Django 5.2.14 on 2026-05-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品名')),
                ('amount', models.PositiveIntegerField(verbose_name='金額（円）')),
                ('category', models.CharField(choices=[('food', '食費・日用品'), ('apparel', '衣服・書籍'), ('gadget', 'ガジェット・趣味'), ('luxury', '嗜好品・課金・コンビニ')], max_length=16, verbose_name='カテゴリ')),
                ('regret_score', models.FloatField(blank=True, null=True, verbose_name='後悔スコア')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': '支出',
                'verbose_name_plural': '支出一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
