# Generated by Django 5.2.14 on 2026-05-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nonExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品名')),
                ('amount', models.PositiveIntegerField(verbose_name='金額（円）')),
                ('category', models.CharField(choices=[('food', '食費・日用品'), ('apparel', '衣服・書籍'), ('gadget', 'ガジェット・趣味'), ('luxury', '嗜好品・課金・コンビニ')], max_length=16, verbose_name='カテゴリ')),
                ('self_control_score', models.FloatField(blank=True, null=True, verbose_name='自己制御スコア')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': '我慢した物',
                'verbose_name_plural': '我慢した物一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
