# Generated by Django 5.2.14 on 2026-06-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_user_nonexpense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='memo',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='expense',
            name='satisfaction',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='満足度'),
        ),
        migrations.AddField(
            model_name='nonexpense',
            name='endurance',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='我慢度'),
        ),
        migrations.AddField(
            model_name='nonexpense',
            name='memo',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
    ]
